BEGIN TRANSACTION;
DROP TABLE IF EXISTS currs;
CREATE TABLE currs (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	to_cur VARCHAR(3) NOT NULL,
	coefficient DECIMAL(5, 2) NOT NULL
);

INSERT INTO currs (to_cur, coefficient)
VALUES
	('USD', 1.00),
	('GBP', 2.00),
	('EUR', 3.00),
	('JPY', 4.00);

DROP TABLE IF EXISTS updates;
CREATE TABLE updates (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	last_update DATETIME NOT NULL
);
COMMIT;
